name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
    - run: curl -s "https://get.sdkman.io" | bash
    - run: |
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk version
            sdk install jbang
            echo 'System.out.println("{\"wrong\":\"very wrong!\"}")' | jbang -
#    - name: Run a one-line script
#      run: echo Hello, world!

    # Runs a set of commands using the runners shell
#    - name: Run a multi-line script
#      run: |
#        echo Add other actions to build,
#        echo test, and deploy your project.
