name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
    - run: curl -s "https://get.sdkman.io" | bash
    - run: |
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install jbang
            echo 'System.out.println("{\"wrong\":\"very wrong!\"}")' | jbang -
